---
title: "Introduction"
---

I am analyzing the statistical relationship between position and awards in baseball. An article looking at how much players were paid sparked my interest in this. The article is in the following link:   http://www.businessinsider.com/mlb-highest-paid-players-2017-6#t3-miguel-cabrera-280-million-24. This is important as it can have implications on contracts of players with determining if players are worth the money as they are likely to be more valuable to their teams. The question do pitchers win more awards when compared to their position player counterparts? It is important to note that on a team there are 8 position players, with at least one back up in case of injury. There are however usually about 13 pitchers on a team making this an almost even comparison.  Pitchers however seem to receive a higher contract number despite Starting pitchers appearing once every five games. Should a player who might only play 25% of the season including the post season be paid every bit as much as other players? Do they win enough awards and make themselves invaluable enough to be seen as deserving of being some of the highest paid players in the league?
