---
title: "Results"
---

The first analysis done is a chi square to look at whether the data was truly a good fit and there was a relationship when comparing the pitchers to the other postions. When comparing these two the following results occurred. 
Pearson's Chi-squared test with Yates' continuity correction

data:  table(Pitcher, Field)
X-squared = 4754.6, df = 1, p-value < 2.2e-16

This chi squared test shows that there is a significant relationship between the two at a very small p value. This does not however inform the finding of more than if these two findings should be considered independently.
Along with this a Kruskal-Wallis test was performed as there are potentially other variables involved such as league and award to see if there is a significant finding when considering these variables. 
kruskal.test(awardID,Position,lgID)

	Kruskal-Wallis rank sum test

data:  awardID and Position
Kruskal-Wallis chi-squared = 586.23, df = 10, p-value < 2.2e-16
Running a Kruskal-Wallis test as there are cateogorical variables preventing a parametric Anova analysis also reveals that there is a significant interaction between the relationship of winning an award and position along with league. 

To test that there is not a confounding factor such as fielder relationship they are removed and the same analysis is run with just pitchers to determine significance.

kruskal.test(awardID,Pitcher,lgID)

	Kruskal-Wallis rank sum test

data:  awardID and Pitcher
Kruskal-Wallis chi-squared = 69.329, df = 1, p-value < 2.2e-16

The p-value still remains significant, though the overall value of the chi-squared decreases indicating this group is not quite as distinct as when considering all of the factors tog-ether suggesting there may be a confounding variable.
It is possible that in these analysis there is also the issue of the changing of award voting and weighting over the years. In addition there is consideration for pitchers in the NL winning awards vs. the AL as the AL removes hitting as a factor for pitcher and used a DH instead adding a position not eligible for awards in the NL.
